#!/bin/sh

set -e

export PGPASSWORD=$POSTGRES_PASSWORD;

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
  CREATE USER $DB_USERNAME WITH PASSWORD '$DB_PASSWORD';

  CREATE DATABASE $DB_DATABASE;

  ALTER ROLE $POSTGRES_USER SET client_encoding TO 'utf8';
  ALTER ROLE $POSTGRES_USER SET timezone TO '$DB_TIMEZONE';

  ALTER ROLE $DB_USERNAME SET client_encoding TO 'utf8';
  ALTER ROLE $DB_USERNAME SET timezone TO '$DB_TIMEZONE';

  GRANT ALL PRIVILEGES ON DATABASE $DB_DATABASE TO $DB_USERNAME;

  ALTER DATABASE $DB_DATABASE set search_path to $DB_DATABASE, public; 

  \c $DB_DATABASE
  GRANT ALL ON SCHEMA public TO $DB_USERNAME;
EOSQL